# This pipeline demonstrates a basic 3 stage CI/CD pipeline. 

stages:
  - build
  - test
  - style

# Only run the pipeline when Python files change (ignore MD)
workflow:
  rules:
    - changes:
        - '*.py'
      when: always
    - when: never

build-image:
  stage: build
  # Use the Docker-in-Docker (DinD) image
  image: docker:stable
  services:
    - docker:dind
  variables:
    # Use TLS for the DinD service
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    # Log in to the GitLab Container Registry
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Building Docker image..."
    # Build the image using the Dockerfile 
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - echo "Pushing Docker image to registry..."
    # Push the image so test jobs can use it
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

run-unit-tests:
  stage: test
  # Use the image built in the 'build-image' job
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script: [] 
  script:
    - echo "Running unit tests inside the Docker container..."
    - python -m pytest -v

run-poc:
  stage: test
  # Use the image built
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script: [] 
  services:
    # Add the RabbitMQ service
    - name: rabbitmq:3-management
      alias: rabbitmq
  variables:
    # Set the environment variable so scripts can find RabbitMQ
    RABBITMQ_HOST: rabbitmq
  script:
    - echo "Running PoC test script (run_poc_test.py) inside the Docker container..."
    - python run_poc_test.py


style-check:
  stage: style
  # Use a basic Python image just for style checking
  image: python:3.11
  before_script:
    - python --version
    - pip install -r requirements.txt
  script:
    - echo "Checking Python syntax (compile all files)..."
    - python -m compileall .
    - echo "Running black in check mode..."
    - black --check --diff .
  allow_failure: false