# This pipeline demonstrates a basic 3 stage CI/CD pipeline. 

stages:
  - style 
  - build
  - test

# Only run the pipeline when Python files change (ignore MD)
workflow:
  rules:
    - changes:
        - 'poc/*.py'
      when: always
    - when: never


style-check:
  stage: style
  # Use a basic Python image just for style checking
  image: python:3.11
  before_script:
    - python --version
    - pip install -r poc/requirements.txt
  script:
    - echo "Checking Python syntax (compile all files)..."
    - python -m compileall poc/
    - echo "Running black in check mode..."
    - black --check --diff poc/
  allow_failure: false

build-image:
  stage: build
  # Use the Docker-in-Docker (DinD) image
  image: docker:stable
  services:
    - docker:dind
  variables:
    # Use TLS for the DinD service
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    # Log in to the GitLab Container Registry
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Building Docker image..."
    # Build the image using the Dockerfile
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA poc/
    - echo "Pushing Docker image to registry..."
    # Push the image so test jobs can use it
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

run-unit-tests:
  stage: test
  # Use the image built in the 'build-image' job
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  before_script: [] 
  script:
    - echo "Running unit tests inside the Docker container..."
    - python -m pytest -v

run-poc:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  services:
    - name: rabbitmq:3-management
      alias: rabbitmq
  variables:
    # This overrides the default 'localhost' in the Python scripts
    RABBITMQ_HOST: rabbitmq

  before_script: [] 

  script:
    - echo "Waiting 10s for RabbitMQ service to initialize..."
    - sleep 10
    - echo "Running the PoC phases test..."
    - cd poc
    - python run_poc_test.py
