version: '3.8'

services:

  # The RabbitMQ message broker service
  rabbitmq:
    image: "rabbitmq:3-management" 
    hostname: "rabbitmq"           
    ports:
      - "5672:5672"   
      - "15672:15672" 
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The FastAPI Ingestion Server
  ingestion-server:
    build: .  
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    environment:
      - RABBITMQ_HOST=rabbitmq 
    depends_on:
      rabbitmq:
        condition: service_healthy # Wait for RabbitMQ to be healthy before starting

  # The Python data consumer
  consumer:
    build: . 
    command: "python consumer.py" 
    environment:
      - RABBITMQ_HOST=rabbitmq '
    depends_on:
      rabbitmq:
        condition: service_healthy 
